on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Archive Release
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ${{ github.event.repository.name }}.zip . -i *.cpp -i *.h -i *.c
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ github.event.repository.name }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
